### ISSUE TITLE
Storage requires login now

### ISSUE THREAD

**Issue by weaseel** [Vip0r/vartastorage#6] opened 2023-11-16 08:52 UTC
Looks like the Varta storage requires a login now. At least my battery got an update.
Will this be supported?

**Comment by Vip0r** [comment] 2024-03-15 20:21
thanks for your PR! As i am anyway already was working on this topics i moved your code into the current release (0.2.7)

before i will adjust the HA-integration it would be great if you can test this authenticate part. (i do not have a device here which is requiring authentication)

**Comment by Vip0r** [comment] 2024-03-26 19:34
@weaseel : Could you check if the current source code in the repo (not the latest release) will works for you?

**Comment by rexxnor** [comment] 2024-03-28 14:21
I have the same storage system and was able to verify that the login code is working as intended (tested on commit 6907829)! Thank you very much for your work!

**Comment by Vip0r** [comment] 2024-03-29 18:33
fixed in v0.3.0

**Closed by Vip0r** 2024-03-29 18:33 UTC
